mysql_connection_python/app/models.py
from __init__ import db

'''
    Classe deve ter o mesmo nome da tabela relacional e seus
atributos devem tem os mesmos nomes de cada coluna da tabela 
'''
class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(30), nullable=False)
    role = db.Column(db.String(20), nullable=False)
    job = db.Column(db.String(20), nullable=False)
    passwd = db.Column(db.String(100), nullable=False)

    def __repr__(self) -> str:
        return f'<Name {self.user_name}>'

mysql_connection_python/app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask

db = SQLAlchemy()

def create_app() -> object:
    '''Instancia um objeto da classe Flask e o retorna para o main.py'''
    
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)

    return app

mysql_connection_python/app/app.py
from __init__ import create_app
from views import views

app = create_app()
app.register_blueprint(views)

if __name__ == '__main__':
    app.run(debug=True) 

mysql_connection_python/app/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from __init__ import db
from models import User

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def index():
    user_list = User.query.order_by(User.id)
    return render_template('index.html', nome='teste.py', users_list=user_list) 

@views.route('/adicionar', methods=['POST'])
def create():
    name = request.form['username']
    password = request.form['password']
    job = request.form['job']
    role = request.form['role']
    
    cadastro = User.query.filter_by(name=name).first()
    if cadastro:
        flash('Usuário já cadastrado.', 'error')
        return redirect(url_for('views.index'))
    
    new_register = User(name=name, passwd=password, job=job, role=role)
    db.session.add(new_register)
    db.session.commit()

    return redirect(url_for('views.index'))

@views.route('/remover', methods=['POST'])
def delete():
    User.query.filter_by(id=request.form['user_id']).delete()
    db.session.commit()
    return redirect(url_for('views.index'))

@views.route('/editar/<int:id>')
def edit(id):
    user = User.query.filter_by(id=id).first()
    return render_template('editar.html', titulo='Editar Dados do Usuário', user=user)

@views.route('/editar/atualizar', methods=['POST'])
def update():
    user = User.query.filter_by(id=request.form['id']).first()

    user.name = request.form['username']
    user.job = request.form['job']  
    user.role = request.form['role']

    db.session.add(user)
    db.session.commit()

    return redirect(url_for('views.index'))

mysql_connection_python/app/templates/editar.html
{% extends 'template.html' %}
{% block content %}
<script>
    $('#select-id').val()
</script>

<section class="container w-50 mt-5">
    <h1>{{ titulo }}</h1>
</section>

<section class="container w-50 my-3">
    <form action="{{ url_for('views.update') }}" method="post">
        <fieldset class="col">
            <input id="hidden-job" type="hidden" value="{{ user.job }}">
            <input id="hidden-role" type="hidden" value="{{ user.role }}">
            <input name="id" value="{{ user.id }}" type="hidden">
            <div class="row my-3">
                <div class="form-group">
                    <label class="form-label" for="username">Nome do Usuário</label>
                    <input name="username" type="text" class="form-control" value="{{ user.name }}">
                </div>
            </div>
            <div class="row my-3">
                <div class="col">
                    <label for="job" class="form-label">Cargos</label>
                    <select name="job" class="form-select" id="select-job" required>
                        <option value="Gerente">Gerente</option>
                        <option value="Auxiliar de Produção">Auxiliar de Produção</option>
                        <option value="Contador">Contador</option>
                        <option value="Recepcionista">Recepcionista</option>
                        <option value="Motorista">Motorista</option>
                        <option value="Telefonista">Telefonista</option>
                        <option value="Vendedor">Vendedor</option>
                    </select>
                </div>
                <div class="col">
                    <label for="role" class="form-label">Permissões</label>
                    <select name="role" class="form-select" id="select-role">
                        <option value="master">Mestre</option>
                        <option value="admin">Administrador</option>
                        <option value="user">Usuário Comum</option>
                    </select>
                </div>
            </div>
            <div class="form-group text-center my-5">
                <a href="{{ url_for('views.index' )}}" class="btn btn-secondary">Cancelar Edições</a>
                <button type="submit" class="btn btn-primary">Atualizar Informações</button>
            </div>
        </fieldset>
    </form>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='script_selects.js') }}"></script>
{% endblock %}

mysql_connection_python/app/templates/index.html
{% extends 'template.html' %}
{% block content %}
<section id="modalRemover" class="modal" tabindex="-1">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="titulo-remover"></h5>
                <button class="btn-close" data-bs-dismiss="modal" aria-label="btn-close"></button>
            </div>
            <form action="{{ url_for('views.delete') }}" method="post">
                <input type="hidden" name="user_id">
                <div class="modal-body">
                    <p>Você realmente deseja excluir esse usuário?</p>
                    <p>Os dados não poderão ser recuperados posteriormente...</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="#modalRemover">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Remover Usuário</button>
                </div>
            </form>
        </div>
    </div>
</section>

<section>
    <div class="container mt-5 mb-3">
        <form action="{{ url_for('views.create')}}" method="post">
            <fieldset class="row align-items-center">
                <div class="col">
                    <label for="username" class="form-label">Username</label>
                    <input name="username" class="form-control" type="text" placeholder="Insira o nome" maxlength="30" required>
                </div>
                <div class="col">
                    <label for="password" class="form-label">Senha</label>
                    <input class="form-control" type="password" name="password" placeholder="Insira uma senha" minlength="16" required>
                </div>
                <div class="col">
                    <label for="job" class="form-label">Cargos</label>
                    <select name="job" class="form-select" required>
                        <option value="Gerente">Gerente</option>
                        <option value="Auxiliar de Produção">Auxiliar de Produção</option>
                        <option value="Contador">Contador</option>
                        <option value="Recepcionista">Recepcionista</option>
                        <option value="Motorista">Motorista</option>
                        <option value="Telefonista">Telefonista</option>
                        <option value="Vendedor">Vendedor</option>
                    </select>
                </div>
                <div class="col">
                    <label for="role" class="form-label">Permissões</label>
                    <select name="role" class="form-select">
                        <option value="master">Mestre</option>
                        <option value="admin">Administrador</option>
                        <option value="user">Usuário Comum</option>
                    </select>
                </div>
                <div class="col">
                    <button type="reset" class="btn btn-secondary">Limpar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </fieldset>
        </form>
    </div>
</section>

<section class="d-flex flex-columns">
    <div class="container text-center">
        <table class="table table-responsive align-middle">
            <thead class="table-dark">
                <tr>
                    <th class="col-sm-1">ID</th>
                    <th class="col-sm-1">Nome usuário</td>
                    <th class="col-sm-1">Função Usuário</th>
                    <th class="col-sm-1">Permissões Usuário</td>
                    <th class="col-sm-1">Ações</th>
                </tr>
            </thead>
            <tbody class="table-striped">
                {% for user in users_list %}
                <tr scope="row col-sm-1">
                    <td> {{ user.id }} </td>
                    <td> {{ user.name }}</td>
                    <td> {{ user.job }}</td>
                    <td> {{ user.role }}</td>
                    <td>
                        <a href="{{ url_for('views.edit', id=user.id) }}" class="btn btn-primary">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <button type="button" data-bs-toggle="modal" data-bs-target="#modalRemover" data-task-id="{{ user.id    }}" class="btn btn-danger">
                            <i class="bi bi-trash"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='script_modal.js') }}"></script>
{% endblock %}

mysql_connection_python/app/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>{{ nome }}</title>
</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>